name: Automated E2E Testing
on: 
  - pull_request
  - workflow_dispatch

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@master
        
      - name: Install
        run: npm i
      
      - name: Build SASS
        run: npm run build

        # - name: Watch
        # run: npm run watch

      - name: run cypress tests with electron
        uses: cypress-io/github-action@v4
        with:
          start: npm run start
          wait-on: "http://127.0.0.1:8080/"
          browser: electron
